TP1/urls.py
from django.contrib import admin
from django.urls import path, include
from ab_1.views import homepage
from Profile.views import profile
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='index'),
    path('program/', include('ab_3.urls')),
    path('homepage/', include('ab_1.urls')),
    path('daftardonatur/', include('ab_4.urls')),
    path('donasikan/', include('ab_2.urls')),
    path('aboutus/', include('ab_5.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
    path('profile', profile, name='profile')
]

ab_1/urls.py
from django.urls import path
from .views import *

app_name = "ab_1"

urlpatterns = [
    path('', homepage, name="homepage"),
    path('logout', logout, name="logout"),
]

ab_4/urls.py
from django.urls import path
from . import views

app_name = "ab_4"

urlpatterns = [
    path('', views.daftardonatur, name="daftardonatur"),
]

ab_5/urls.py
from django.urls import path
from . import views

app_name = "ab_5"

urlpatterns = [
    path('', views.aboutus, name="aboutus"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Mada:700|Nunito:700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    {% block head %}
        <!-- head -->
    {% endblock %}
    <title>
        {% block title %}
        <!-- title -->
        {% endblock %}
    </title>
    
    <!-- bootstrap csss -->
</head>

<body>
    <nav>
        {% include "navbar.html" %}
    </nav>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        {% include "footer.html" %}
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/footer.html
<div class="py-5 bg-dark" style="background-color: #00c6cf !important">
      <div class="container">
      	<div class="row ftr text-justify">
      		<div class="col-lg-3 col-md-12 col-sm-12 col-12">
						<h6><span style="color:#F77600">AyoBantu </span>by SinarPerak</h6>
						<p class="m-0">Kampus UI Depok, Pondok Cina, Beji, Kota Depok, Jawa Barat 16424</p>
						<p class="m-0">0812-7734-890</p>
						<p class="m-0">contact@ayobantu.com</p><br>
			  	</div>
			  <div class="col-sm col-md-2 col-lg-3"></div>
			  <div class="col-sm-12 col-lg-6 col-sm-8">
				<h6>Tentang<span style="color:#F77600"> AyoBantu</span></h6>
				<p class="m-0">AyoBantu adalah platform crowdfunding dibawah yayasan SinarPerak yang bertujuan untuk membantu
					penggalangan dana bagi orang yang membutuhkan di lokasi-lokasi bencana. 
				</p>
			  </div>
			  
				 
			  </div>
			  <div class="row">
				  <div class="col-4"></div>
					<div class="col-4 col-md">
						  <div class="text-center">
								  <h6 class="mb-3 cr" style="color: #078488 !important;
								  padding-top:30px;">AyoBantu by SinarPerak © 2018</h6>
						  </div>
					</div>
					<div class="col-4 sc text-right">
						<h6>Temukan kami di</h6>
						<div style="display:flex;">
							<ul class="social-network social-circle">
								<li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
						
					</div>
      	</div>
        
	  </div>
</div>

templates/navbar.html
<div class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top" style="background-color: #00c6cf !important">
      <div class="container">
        <a class="navbar-brand text-white" href={% url 'ab_1:homepage' %}>AyoBantu</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {%if user.is_authenticated%}
              <li class="nav-item">
                  <a class="nav-link text-white" href={% url 'ab_5:aboutus' %}>About Us</a>
              </li>
              <li class="nav-item">
                <a href="{%url 'profile'%}" class="nav-link text-white">Halo, {{user.first_name}} {{user.last_name}}</a>
              </li>
              <li class=" mx-3 nav-item">
                  <a href= "{% url 'ab_1:logout'%}" class="nav-link text-white">Log Out</a>
              </li>


              {%else%}
              <li class="nav-item">
                <a class="nav-link text-white" href={% url 'ab_5:aboutus' %}>About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href={% url 'ab_4:daftardonatur' %}>Daftar Donatur</a>
              </li>
              {%endif%}
          </ul>
        </div>
      </div>
    </div>